### ISSUE TITLE
Help needed with launching the app via ./start_app.sh

### ISSUE THREAD

**Issue by manish-frustated** [theowni/Damn-Vulnerable-RESTaurant-API-Game#3]
┌──(root㉿kali)-[/opt/Damn-Vulnerable-RESTaurant-API-Game]
└─# ./start_app.sh        
docker: 'compose' is not a docker command.
See 'docker --help'

**Comment by theowni** [comment]
Hi @manish-frustated,
thanks for raising the issue.

Your problem is related with Docker Compose V2 which is not installed on your Kali. You probably have Docker Compose V1.
From July 2023 Compose V1 stopped receiving updates, so I decided to use `docker compose` instead of  `docker-compose` in this project.

Here is the documentation describing the migration process to Docker Compose V2:
https://docs.docker.com/compose/migrate/

Let me know if installing new version of Docker Compose resolves the issue. Hope it helps!

**Comment by manish-frustated** [comment]
DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
mkdir -p $DOCKER_CONFIG/cli-plugins
curl -SL https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
sudo mkdir -p /usr/local/lib/docker/cli-plugins
sudo mv $DOCKER_CONFIG/cli-plugins/docker-compose /usr/local/lib/docker/cli-plugins/
sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
docker compose version

**Now my docker version is 2.26.1**

then i start the app
-------------------------------------------------------------------------------------------------------------------------
./start_app.sh
WARN[0000] /opt/Damn-Vulnerable-RESTaurant-API-Game/docker-compose.yml: `version` is obsolete 
[+] Running 2/0
 ✔ Container damn-vulnerable-restaurant-api-game-db-1   Created                                                                                        0.0s 
 ✔ Container damn-vulnerable-restaurant-api-game-web-1  Created                                                                                        0.0s 
Attaching to db-1, web-1
db-1   | 
db-1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
db-1   | 
db-1   | 2024-04-11 06:18:48.175 UTC [1] LOG:  starting PostgreSQL 15.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
db-1   | 2024-04-11 06:18:48.175 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1   | 2024-04-11 06:18:48.175 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1   | 2024-04-11 06:18:48.191 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1   | 2024-04-11 06:18:48.206 UTC [24] LOG:  database system was shut down at 2024-04-11 06:18:44 UTC
db-1   | 2024-04-11 06:18:48.216 UTC [1] LOG:  database system is ready to accept connections
web-1  | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
web-1  | INFO  [alembic.runtime.migration] Will assume transactional DDL.
web-1  | INFO:     Will watch for changes in these directories: ['/app']
web-1  | INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
web-1  | INFO:     Started reloader process [1] using WatchFiles
web-1  | /app/.venv/lib/python3.8/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
web-1  | * 'orm_mode' has been renamed to 'from_attributes'
web-1  |   warnings.warn(message, UserWarning)
web-1  | INFO:     Started server process [10]
web-1  | INFO:     Waiting for application startup.
web-1  | INFO:     Application startup complete.

but still not able to access it  from any interface
this is the content of my ipconfig

br-8cafce940df6: 
        inet 172.19.0.1  

br-e3a81fb59fed: 
        inet 172.18.0.1  

docker0: 
        inet 172.17.0.1  

eth0: 
        inet 172.20.181.201  

lo: 
        inet 127.0.0.1  

veth5fd012d: 
        inet6 fe80::cc70:1eff:fe99:401e  

vethfde602e: 
        inet6 fe80::6817:5cff:fe5a:73f

**Comment by theowni** [comment]
Based on the output in the console that you presented, containers are running fine and the web application should be available on `http://localhost:8080/`.

It's described in the README:
```
The API service will be exposed at http://localhost:8080/ by default. API documentation can be found at the following endpoints:

Swagger - http://localhost:8080/docs
Redoc - http://localhost:8080/redoc
```

At this point, you can start hacking, enjoy :)
